baseURL = "https://xavierleduc.github.io/"
languageCode = "fr-fr"
title = "Xavier LEDUC"
theme = "Hugo Noir"

[taxonomies]
  tag = "tags"
  category = "categories"

[params]
  defaultTheme = "auto"
  ShowReadingTime = true
  ShowPostNavLinks = true
  ShowBreadCrumbs = true
  ShowCodeCopyButtons = true
  ShowRssButtonInSectionTermList = true
  ShowToc = true

[[menu.main]]
  identifier = "posts"
  name = "Articles"
  url = "/posts/"
  weight = 10

[[menu.main]]
  identifier = "tags"
  name = "Tags"
  url = "/tags/"
  weight = 20

[[menu.main]]
  identifier = "categories"
  name = "Catégories"
  url = "/categories/"
  weight = 30

[markup.goldmark.renderer]
  unsafe = true
